name: Clear Attendance Collection

on:
  schedule:
    - cron: '30 18 * * *' 
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X DELETE "https://employee-management-system-backend-beryl.vercel.app/clear-attendance" \
          -H "authkey: ${{ secrets.AUTH_KEY }}"
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
