name: Clear Attendance Collection

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X POST "https://your-vercel-app.vercel.app/api/clear-collection" \
          -H "Authorization: ${{ secrets.AUTH_KEY }}"
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
